# Generated by Django 2.2.13 on 2020-06-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peekaboo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('arrival_time', models.TimeField()),
                ('leave_time', models.TimeField()),
                ('breakfast', models.BooleanField(default=True)),
                ('brunch', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('supper', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peekaboo.Child')),
            ],
        ),
    ]
