# Generated by Django 2.2.13 on 2020-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peekaboo', '0002_auto_20200612_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='leave_time',
            field=models.TimeField(null=True),
        ),
    ]
