# Generated by Django 2.2.13 on 2020-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peekaboo', '0003_auto_20200612_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='leave_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
